services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped

    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/New_York

    volumes:
      - /volume1/docker/radarr/config:/config
      - /volume1/media:/data

    ports:
      - "7878:7878"

    networks:
      - media

networks:
  media:
    external: true
