- Homelab:
    - GitHub:
        - abbr: GH
          href: https://github.com/shen3340/Homelab

    - Documentation:
        - abbr: DOCS
          href: https://docs.shen3340.com

    - Public Status:
        - abbr: STATUS
          href: https://status.shen3340.com
