services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - /volume1/docker/jellyfin/config:/config
      - /volume1/docker/jellyfin/cache:/cache
      - /volume1/media:/media
    networks:
      - media
      - proxy
    environment:
      - TZ=America/new_york

networks:
  media:
    external: true
  proxy:
    external: true
