services:
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer

    restart: unless-stopped

    environment:
      PORTAINER_LICENSE_KEY: ${PORTAINER_LICENSE_KEY}

    ports:
      - "7000:9443"

    volumes:
      - /volume1/docker/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - docker_default
      - internal

networks:
  docker_default:
    external: true

  internal:
    external: true
